---
# tasks file for selinux-pgsql
- block: ### Debial only ### 
    - name: Install selinux utils and postgresql
      apt: 
        pkg:
        - python3-selinux
        - policycoreutils
        - postgresql
        - postgresql-contrib
  when: ansible_os_family == "Debian"

- block: ### RHEL only ###
    - name: Install postgresql
      yum:
        name:
        - postgresql-server
        - postgresql-contrib
    - name: Postgresql init database
      shell: postgresql-setup initdb
  when: ansible_os_family == "RedHat"

- name: Start and enable startup  postgresql service
  systemd:
    name: postgresql
    state: started
    enabled: yes

- name: Disable SELinux
  selinux:
    state: disabled
  notify:
    - Restart server

